version: '3.7'
services:
  gpixel:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn gpixel.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./gpixel/:/var/www/gpixel/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=gpixel
    - POSTGRES_PASS=gpixel
    - POSTGRES_DB=gpixel
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
    - 1337:80
    depends_on:
    - gpixel

volumes:
 postgres_data:

