# Generated by Django 2.2.6 on 2019-11-22 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 16, 19, 17, 39238, tzinfo=utc), verbose_name='date published'),
        ),
    ]
