# Generated by Django 2.2.7 on 2020-01-01 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='domain',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='pixel.Domain'),
        ),
    ]
