# Generated by Django 2.2.6 on 2019-11-22 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0002_auto_20191122_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 16, 22, 46, 292117, tzinfo=utc), verbose_name='date published'),
        ),
    ]
