# Generated by Django 2.2.7 on 2020-01-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0003_auto_20200102_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevisit',
            old_name='referer',
            new_name='url_path',
        ),
    ]
