# Generated by Django 2.2.6 on 2019-11-23 16:51

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0003_auto_20191122_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialseries',
            name='category',
        ),
        migrations.AddField(
            model_name='requests',
            name='city_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='device',
            field=models.CharField(default=datetime.datetime(2019, 11, 23, 16, 51, 46, 161109, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.DeleteModel(
            name='TutorialCategory',
        ),
        migrations.DeleteModel(
            name='TutorialSeries',
        ),
    ]
