# Generated by Django 2.2.7 on 2019-11-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0004_auto_20191123_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('agent', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('device', models.CharField(max_length=200)),
                ('country_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=200)),
                ('time_opened', models.DateTimeField(verbose_name='time opened')),
            ],
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
