# Generated by Django 2.2.7 on 2020-01-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0005_auto_20200105_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='domain_name',
            new_name='name',
        ),
    ]
