# Generated by Django 2.2.7 on 2019-11-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0005_auto_20191123_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='time_opened',
            field=models.DateTimeField(verbose_name='time_opened'),
        ),
    ]
