# Generated by Django 2.2.7 on 2019-11-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0006_auto_20191123_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='username',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
