# Generated by Django 2.2.7 on 2019-11-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0007_pagevisit_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevisit',
            name='username',
        ),
    ]
