# Generated by Django 2.2.7 on 2020-01-05 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pixel', '0008_auto_20200105_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='users',
        ),
        migrations.AddField(
            model_name='domain',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
