# Generated by Django 2.2.7 on 2019-11-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0008_remove_pagevisit_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevisit',
            old_name='city_name',
            new_name='region_name',
        ),
    ]
