# Generated by Django 2.2.7 on 2020-01-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0010_auto_20200105_1528'),
        ('pixel', '0010_auto_20200106_0134'),
    ]

    operations = [
    ]
